def Unit2():
  TestedApps.Orders.Run()
  Aliases.Orders.MainForm.MainMenu.Click("Orders|New order...")
  Aliases.Orders.OrderForm.Group.Customer.click()
  Aliases.Orders.OrderForm.Group.Customer.setText("sonia")
  Aliases.Orders.OrderForm.Group.Street.Click()
  Aliases.Orders.OrderForm.Group.Street.setText("str1")
  Aliases.Orders.OrderForm.Group.City.Click()
  Aliases.Orders.OrderForm.Group.City.setText("HYd")
  Aliases.Orders.OrderForm.Group.State.Click()
  Aliases.Orders.OrderForm.Group.State.setText("Ap")
  Aliases.Orders.OrderForm.Group.CardNo.click()
  Aliases.Orders.OrderForm.Group.CardNo.setText("2345544")
  Aliases.Orders.OrderForm.Group.Zip.Click()
  Aliases.Orders.OrderForm.Group.Zip.SetText("567654")
  Aliases.Orders.OrderForm.ButtonOK.Click()
  Aliases.Orders.MainForm.Close()
  Aliases.Orders.dlgConfirmation.btnNo.ClickButton()